export const SEARCH_FETCH = 'SEARCH_FETCH';
export const SEARCH_FETCH_SUCCESS = 'SEARCH_FETCH_SUCCESS';
export const SEARCH_FETCH_ERROR = 'SEARCH_FETCH_ERROR';

export const SET_PROVIDER_DATA = 'SET_PROVIDER_DATA';
